### ISSUE TITLE
Kick-off

### ISSUE THREAD

**Issue by diervo** [HTMLParseErrorWG/meta#1]
@inikulin Do you think a kickoff meeting over hangouts/others would make sense to coordinate the first steps? I see you already begun the work, so I could probably start helping this weekend.

**Comment by inikulin** [comment]
Hi,

Sorry for the delay in response. I was hoping to accomplish preparation steps before the next week, but circumstances kept me away from computer for the most part of the weekend. I've only managed to accomplish some basic refactorings. For now I need to implement error reporting feature for parse5 and setup testing for it. After that we can start work on spec and html5lib tests. This is the point there we can split our job into chunks and do it in parallel. Give me a couple of days to deal with remaining preparation and then we can organize the meeting to discuss further steps.

**Comment by diervo** [comment]
Sounds good, no rush.

**Comment by inikulin** [comment]
@diervo It took a bit longer than I expected, but I guess I've finally sorted things out and work should go smoothly now. I've created guidelines on how to participate: https://github.com/HTMLParseErrorWG/meta/blob/master/WORKFLOW.md Please, let me know if you have any questions.

**Comment by diervo** [comment]
@inikulin Awesome! Very well detailed, and also having already an example helps a lot.
Will try to find some time over the week to start with a couple. Worst case weekend.
