### ISSUE TITLE
Figure out tokenizer error format in html5lib tests

### ISSUE THREAD

**Issue by inikulin** [HTMLParseErrorWG/meta#2]
Currently errors in tokenizer tests reported as `"ParseError"` tokens without any particular details. I'm planning to add `errors` array field to test cases, so it will be:
```json
{
    "description":"Truncated doctype start",
    "input":"<!DOC>", 
    "output":[["Comment", "DOC"]],
    "errors": ["(1, 3) some-error-code"]
}
```

Should we remove `"ParseError"` pseudo tokens along the way?
\cc @gsnedders

**Comment by gsnedders** [comment]
Given we're JSON, I think I'd go for something like:

```
[{line: 1,
  col: 3,
  code: "some-error-code"}]
```

But yeah, removing the ParseError "tokens" is probably reasonable.

**Comment by inikulin** [comment]
Shouldn't we be consistent with tree construction error format where we have `(line, col) err-code` strings? Proposed format is fine for me, just asking if consistency should be a subject of concern here.

**Comment by gsnedders** [comment]
I don't think so. You already need different handlers for both, and I think it makes more sense to have a directly machine-readable form than having a fixed syntax that then gets parsed out of it?

**Comment by inikulin** [comment]
Makes sense, we'll stick with format proposed in https://github.com/HTMLParseErrorWG/meta/issues/2#issuecomment-287727473 then.
