### ISSUE TITLE
Should we use location ranges for tree construction error in html5lib-tests?

### ISSUE THREAD

**Issue by inikulin** [HTMLParseErrorWG/meta#4]
I came to conclusion that giving just end location of the token that caused an error is not quite informative. Thus, existing validators (e.g. https://html5.validator.nu/) highlight whole token. I suggest to use location range for the token in errors for tree construction stage, e.g.:
`(1,2-1,5): some-error`. 
On the other hand, for tokenizer is still fine to use single location point.
@gsnedders what do you think?

**Comment by inikulin** [comment]
Or even better:
`(1:9-1:24) self-closing-non-void-html-element`

It resembles location format usually used in editors, where `:` serves as a line/col separator

**Comment by inikulin** [comment]
Waiting for @gsnedders feedback

**Comment by gsnedders** [comment]
Whatever is fine with me, really, provided it is trivially parsable! Sorry for missing this before, been busy with the csswg-test merge.

**Comment by inikulin** [comment]
@gsnedders Awesome, thanks!
