### ISSUE TITLE
Implement tokenizer errors

### ISSUE THREAD

**Issue by inikulin** [HTMLParseErrorWG/meta#5]
- [x] Add errors for all states
- [x] Remove `ParseErrors` from tokenizer tests (https://github.com/HTMLParseErrorWG/html5lib-tests/pull/16)
- [x] Add note about purpose of IDs in spec
- [x] Add acknowledges to the spec (https://github.com/HTMLParseErrorWG/html/pull/15)
- [x] Issue PRs to upstreams

**Comment by inikulin** [comment]
I wonder if we should create dedicated "Parse errors" section in spec in which we'll add table with error definitions and brief non-normative descriptions. Thus, errors in states will reference definitions in table.
Alternatively, we can do it once we'll have all errors done, including tree construction stage.
@diervo What do you think?

**Comment by diervo** [comment]
@inikulin I wanted to ask about some better or centralized way to display errors, because I found kind of hard to read them in the current form. 

I don't have much background as a spec writer, but a table sounds good, and I doubt that someone will be oppose to it? From semantics perspective, not sure if we should add it to the main page or an  annex or something?

**Comment by diervo** [comment]
@inikulin Also what else I can help you with? 
I can try to spec out the table if you want, or do the `/` error if we have consensus on it.
What else is left?

**Comment by inikulin** [comment]
@diervo Already started working on it, check it out: 
https://htmlparseerrorwg.github.io/html-build/output/multipage/syntax.html#parse-errors

> @inikulin Also what else I can help you with?
I can try to spec out the table if you want, or do the / error if we have consensus on it.

I guess I can take care of the table. Regarding `/` error: we need to issue it to the upstream first, so it's a bit tricky at the moment: I'd like to have everything ready and rebased before to simplify further rebase. The best thing that can be done at the moment is a triple check everything for possible editorial nits.

**Comment by diervo** [comment]
Will do, I will also ask someone in my team to do it, external eyes might help to catch small things.

**Comment by diervo** [comment]
@inikulin Sent the PR (and you merged it) for the remanning issues we found.
What else is there blocking the merge?

**Comment by inikulin** [comment]
@diervo I'm working on error table we've discussed previously. A few last days were quite intense and I had only a bit of time on nights to work on it. I hope I'll finish it in 2-3 days.

**Comment by inikulin** [comment]
Afterwards we'll need to rebase all repos master branches on top of upstream and we'll be ready to go.

**Comment by inikulin** [comment]
The PRs to HTML standard and html5lib-tests suite were merged.
