### ISSUE TITLE
Missing colon in new-error format & duplication?

### ISSUE THREAD

**Issue by diervo** [HTMLParseErrorWG/meta#6]
I noticed that we are missing the `:` in the new-errors after the (line:col) pattern.

Example:
```
#errors
(1,33): invalid-character-in-attribute-name
#new-errors
(1:24) invalid-character-in-attribute-name
```

I'm following the same pattern for now, so its easier to change it later all, at once in case is incorrect.

Moreover, sometimes we already have the same error, but tests will fail unless `#new-errors` with the same string is added. It looks like we might need to do a lookup merge for the old? Again, for now following the same pattern which we can probably reconcile later.

**Comment by inikulin** [comment]
Don't pay attention to old errors. Their error codes are quite random and location info is incorrect. I've explained location format in #4
