### ISSUE TITLE
DOCTYPE Errors

### ISSUE THREAD

**Issue by diervo** [HTMLParseErrorWG/meta#9]
@inikulin I started to make a dent to the doctype errors (which is the only thing we have left 😺), but I want to run a couple of things by you before wasting time:

I see that there are a bunch of omitted branch-checks (I assume because you didn't need them before having the explicit error calls). 

For example in `BEFORE_DOCTYPE_PUBLIC_IDENTIFIER_STATE`, `eof` branch is missing. 
My assumption is that now, we need those checks, as per spec back, correct?

Same goes for states missing such as  `After DOCTYPE public keyword state`, again same thing missing since without errors codepath just matched.

My assumption is that we need in this case as well, to bring this state back to disambiguate errors for missing space.

So let me know if you want me to help completing all those changes this week (specifically the missing pieces in parse5), or you rather want to finish it up, and ship all the things! :)

**Comment by inikulin** [comment]
@diervo There were lots of cosmetic changes to spec since tokenizer was implemented and some branches were omitted due to the absence of error reporting. I'll go through doctype states and align them with spec.
